server:
  port: 8765
spring:
  application:
    name: service-feign
  cloud:
    config:
      name: config-client
      profile: dev
      label: master
      uri: http://localhost:8888
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true